[book]
authors = ["薛继鹏"]
multilingual = false
src = "src"
title = "Kubebuilder Book 中文文档"

[output.html]
google-analytics = "UA-119864590-1"
curly-quotes = true

[preprocessor.literatego]
command = "./litgo.sh"

[preprocessor.markerdocs]
command = "./markerdocs.sh"
